
$('div#chargement').html('Chargement.... ');
$('div#Filtrerlesindividus').html('Filtrer les individus ');
$('label[for=touslesindividus]').html('Tous les individus');
$('label[for=ascendant]').html('Les ascendants ');
$('label[for=descendant]').html('Les descendants ');
$('label[for=individusmarque]').html('Les individus marqués ');
$('div#Filtrerlesevenements').html('Filtrer les événements');
$('label[for=tous]').html('Tous');
$('label[for=evenement_majeurs]').html('Les événements majeurs');
$('div#Modesdereprésentation').html('Modes de représentation ');
$('label[for=densite]').html('Densité ');
$('label[for=parperiode]').html('Par période ');
$('label[for=pargeneration]').html('Par génération ');
$('a#boutonindividus').html('Individus ');
$('a#boutonlieu').html('Lieu ');
$('option[value=A]').html('Tous les lieux');
$('option[value=B]').html('Lieux plus representés');
$('option[value=C]').html('Lieux non géolocalisés');
$('option[value=D]').html('Lieux visibles');
$("#nom").attr("placeholder", "Nom");
$("#prenom").attr("placeholder", "Prenom");
$("#lieu").attr("placeholder", "Lieu");
//textTraduit='cliquer pour voir un evenement pour ';
$('.trigger:eq(0)').html('Filtrer les individus');
$('.trigger:eq(1)').html('Filtrer les événements');
$('.trigger:eq(2)').html('Modes de représentation');
$('.trigger:eq(3)').html("Options d'affichage");
$('.trigger:eq(4)').html('Impression');
$('#carte').attr('value','Carte');
$('#Liste_eclaire').attr('value','Liste éclair');
$('label[for=POI]').html('Points d\'intérêt ');
$('label[for=Legende]').html('Légende ');
$('label[for=nombrerecherche]').html('Recherche');
$("div#boutonplaypause #start .mesimages").attr("title", "Lecture");
$("div#boutonplaypause2 #start2 .mesimages").attr("title", "Lecture");
$("div#boutonplaypause #stop .mesimages").attr("title", "Stop");
$("div#boutonplaypause2 #stop2 .mesimages").attr("title", "Stop");
$(document).attr("title", "Répartition géographique");
//textTraduit='clik to see  even for ';